server.port=8084

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=health_user
spring.datasource.password=pass123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true