DROP DATABASE LINK pg_link;

CREATE DATABASE LINK pg_link 
CONNECT TO "postgres" IDENTIFIED BY "pass123" 
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=PostgresDSN))(HS=OK))';