### REST Data HTTP service
server.port=8095
server.servlet.context-path=/DSA-DOC-JSONService/rest

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=info

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis
json.data.source.file.path=C:/Users/formg/Downloads/DSA-DOC-JSONService/DSA-DOC-JSONService/src/main/resources/datasource/ExtraMedicalData.json
